#!/usr/bin/env bash
# install.sh - Scanner module installation script
# Sets up scanner shortcuts for desktop Macs with scanner access

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source required libraries
# shellcheck source=../../lib/logging.sh
source "${SCRIPT_DIR}/../../lib/logging.sh"
# shellcheck source=../../lib/utils.sh
source "${SCRIPT_DIR}/../../lib/utils.sh"

# Configuration
SCANNER_CONFIG="${HOME}/.scanner-config"
INSTALL_PREFIX="/usr/local/bin"
TEMPLATE_FILE="${SCRIPT_DIR}/templates/scan-shortcuts.sh.template"

# Scanner command names
SCANNER_COMMANDS=(
    "scan-document"
    "scan-photo"
    "scan-multipage"
    "scan-test"
    "scan-config"
)

#######################################
# Read scanner host from config file
# Returns:
#   Scanner host string, or empty if not found
#######################################
get_scanner_host() {
    if [[ -f "${SCANNER_CONFIG}" ]]; then
        grep "^SCANNER_HOST=" "${SCANNER_CONFIG}" 2>/dev/null | cut -d'=' -f2- | tr -d '"' | tr -d "'"
    fi
}

#######################################
# Save scanner host to config file
# Arguments:
#   $1 - Scanner hostname/IP
#######################################
save_scanner_host() {
    local host="$1"
    cat > "${SCANNER_CONFIG}" << EOF
# Scanner configuration
# This file is automatically generated and not tracked in the dotfiles repo
SCANNER_HOST="${host}"
EOF
    print_success "Scanner configuration saved to ${SCANNER_CONFIG}"
}

#######################################
# Render template with scanner host
# Arguments:
#   $1 - Scanner hostname/IP
#   $2 - Output file path
# Returns:
#   0 if successful, 1 otherwise
#######################################
render_template() {
    local host="$1"
    local output_file="$2"

    if [[ ! -f "${TEMPLATE_FILE}" ]]; then
        print_error "Template file not found: ${TEMPLATE_FILE}"
        return 1
    fi

    # Replace {{SCANNER_HOST}} with actual hostname
    sed "s|{{SCANNER_HOST}}|${host}|g" "${TEMPLATE_FILE}" > "${output_file}"

    if [[ -f "${output_file}" ]]; then
        chmod +x "${output_file}"
        return 0
    else
        print_error "Failed to render template to ${output_file}"
        return 1
    fi
}

#######################################
# Install scanner shortcuts
# Arguments:
#   $1 - Scanner hostname/IP
# Returns:
#   0 if successful, 1 otherwise
#######################################
install_scanner_shortcuts() {
    local host="$1"
    local temp_script
    temp_script=$(mktemp)

    print_status "Installing scanner shortcuts..."

    # Render template to temporary file
    if ! render_template "${host}" "${temp_script}"; then
        rm -f "${temp_script}"
        return 1
    fi

    # Check if we need sudo for /usr/local/bin
    local use_sudo=""
    if [[ ! -w "${INSTALL_PREFIX}" ]]; then
        print_status "Need sudo privileges to install to ${INSTALL_PREFIX}"
        use_sudo="sudo"
    fi

    # Install each command as a symlink to the same script
    # The script determines behavior based on how it's called (basename)
    local main_script="${INSTALL_PREFIX}/scan-shortcuts"

    # Copy the rendered template to main script location
    if [[ -n "${use_sudo}" ]]; then
        ${use_sudo} cp "${temp_script}" "${main_script}"
        ${use_sudo} chmod +x "${main_script}"
    else
        cp "${temp_script}" "${main_script}"
        chmod +x "${main_script}"
    fi

    print_success "Installed main script: ${main_script}"

    # Create symlinks for each command
    for cmd in "${SCANNER_COMMANDS[@]}"; do
        local cmd_path="${INSTALL_PREFIX}/${cmd}"

        # Remove existing symlink/file if present
        if [[ -e "${cmd_path}" || -L "${cmd_path}" ]]; then
            if [[ -n "${use_sudo}" ]]; then
                ${use_sudo} rm -f "${cmd_path}"
            else
                rm -f "${cmd_path}"
            fi
        fi

        # Create symlink
        if [[ -n "${use_sudo}" ]]; then
            ${use_sudo} ln -s "${main_script}" "${cmd_path}"
        else
            ln -s "${main_script}" "${cmd_path}"
        fi

        print_success "  ${cmd}"
    done

    # Clean up temp file
    rm -f "${temp_script}"

    return 0
}

#######################################
# Test scanner connection (optional)
# Returns:
#   0 if successful, 1 otherwise (non-fatal)
#######################################
test_scanner_connection() {
    print_status "Testing scanner connection..."

    if command_exists scan-test; then
        if scan-test; then
            return 0
        else
            print_warning "Scanner connection test failed"
            print_warning "You can test again later with: scan-test"
            return 1
        fi
    else
        print_warning "scan-test command not found, skipping connection test"
        return 1
    fi
}

#######################################
# Main installation function
#######################################
main() {
    print_section "Installing Scanner Module"

    # Check if running on desktop (not laptop)
    if is_laptop; then
        print_warning "This module is designed for desktop Macs"
        echo ""
        if ! confirm "Continue installation anyway?" "n"; then
            print_status "Installation cancelled"
            return 0
        fi
    fi

    # Check if scanner host is already configured
    local scanner_host
    scanner_host=$(get_scanner_host)

    if [[ -n "${scanner_host}" ]]; then
        print_status "Scanner already configured: ${scanner_host}"
        echo ""
        if ! confirm "Reconfigure scanner host?" "n"; then
            print_status "Using existing configuration: ${scanner_host}"
        else
            # Prompt for new scanner host
            echo ""
            scanner_host=$(prompt_input "Scanner server hostname or IP" "${scanner_host}")

            if [[ -z "${scanner_host}" ]]; then
                print_error "Scanner hostname is required"
                return 1
            fi

            # Save configuration
            save_scanner_host "${scanner_host}"
        fi
    else
        # First time setup - prompt for scanner host
        echo ""
        print_status "Scanner shortcuts allow you to scan documents and photos from the command line"
        print_status "You need a scanner server (hostname or IP address) to connect to"
        echo ""

        scanner_host=$(prompt_input "Scanner server hostname or IP")

        if [[ -z "${scanner_host}" ]]; then
            print_error "Scanner hostname is required"
            return 1
        fi

        # Save configuration
        save_scanner_host "${scanner_host}"
    fi

    print_success "Scanner host: ${scanner_host}"
    echo ""

    # Install scanner shortcuts
    if ! install_scanner_shortcuts "${scanner_host}"; then
        print_error "Failed to install scanner shortcuts"
        return 1
    fi

    echo ""
    print_success "Scanner shortcuts installed successfully!"
    echo ""
    print_status "Available commands:"
    print_status "  scan-document   - Scan single document as PDF (flatbed)"
    print_status "  scan-photo      - Scan photo as high-res JPG"
    print_status "  scan-multipage  - Scan multiple pages as PDF (ADF)"
    print_status "  scan-test       - Test scanner connection"
    print_status "  scan-config     - Show scanner configuration"
    echo ""

    # Check if SANE is installed
    if ! command_exists scanimage; then
        print_warning "scanimage command not found"
        print_status "SANE backends are required for scanner functionality"
        echo ""
        if confirm "Install SANE backends via Homebrew?" "y"; then
            print_status "Installing sane-backends..."
            if command_exists brew; then
                if brew install sane-backends; then
                    print_success "SANE backends installed"
                else
                    print_error "Failed to install SANE backends"
                    print_status "Install manually: brew install sane-backends"
                fi
            else
                print_error "Homebrew not found"
                print_status "Install manually: brew install sane-backends"
            fi
        else
            print_warning "Scanner commands will not work without SANE backends"
            print_status "Install later with: brew install sane-backends"
        fi
        echo ""
    else
        print_success "SANE backends are installed"

        # Optionally test scanner connection
        echo ""
        if confirm "Test scanner connection now?" "y"; then
            test_scanner_connection
        fi
        echo ""
    fi

    print_success "Scanner module installation completed"
    print_status "Scanned files will be saved to: ${HOME}/Documents/Scans/"
}

# Run main function
main "$@"
